name: Continuous Integration

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./

      - name: Log the outputs
        run: |
          echo ${{ toJSON(toJSON(steps.test-action.outputs)) }}

      - name: PR should have been found
        if: ${{ steps.test-action.outputs.number == '' }}
        run: exit 1
